"""HTML report generator — terminal-styled, dark, zero dependencies."""

from __future__ import annotations

import html as _html
from pathlib import Path

from ..core.models import Finding, ScanRecord
from .. import __version__

SEV_COLOR = {
    "high": "#ff3b30",
    "medium": "#ff9f0a",
    "low": "#ffd60a",
    "info": "#30d158",
}
SEV_ROW = {
    "high": "background:rgba(255,59,48,.09)",
    "medium": "background:rgba(255,159,10,.08)",
    "low": "background:rgba(255,214,10,.07)",
    "info": "background:rgba(48,209,88,.06)",
}


def _esc(s: str) -> str:
    return _html.escape(str(s), quote=True)


def _sev_badge(sev: str) -> str:
    return (f'<span class="badge" style="color:{SEV_COLOR.get(sev, "#888")};'
            f'border:1px solid {SEV_COLOR.get(sev, "#888")}55">{sev.upper()}</span>')


def _findings_table(findings: list[Finding]) -> str:
    if not findings:
        return '<p class="muted">No findings. Either the target is clean or the scan was shallow.</p>'
    rows = []
    for f in Finding.dedupe(findings):
        rows.append(
            f'<tr style="{SEV_ROW.get(f.severity, "")}">'
            f"<td>{_sev_badge(f.severity)}</td>"
            f"<td class=c>{_esc(f.category)}</td>"
            f"<td class=c>{_esc(f.host)}{f'::{f.port}' if f.port else ''}</td>"
            f"<td>{_esc(f.title)}<div class=sub>{_esc(f.detail)}</div></td>"
            "</tr>"
        )
    return (
        "<table><thead><tr><th>SEV</th><th>TYPE</th><th>TARGET</th><th>FINDING</th></tr></thead>"
        + "<tbody>" + "".join(rows) + "</tbody></table>"
    )


def render_html(record: ScanRecord) -> str:
    counts = {}
    for f in record.findings:
        counts[f.severity] = counts.get(f.severity, 0) + 1
    high = counts.get("high", 0)
    med = counts.get("medium", 0)

    if high:
        verdict, vcolor = "WEAK SURFACE — HIGH FINDINGS", SEV_COLOR["high"]
    elif med:
        verdict, vcolor = "NOTABLE ISSUES", SEV_COLOR["medium"]
    else:
        verdict, vcolor = "NO CRITICAL SURFACE", SEV_COLOR["info"]

    stat = lambda k: f'<div class="stat"><div class="n" style="color:{SEV_COLOR.get(k, "#eaeaea")}">{counts.get(k, 0)}</div><div class="l">{k}</div></div>'

    return f"""<!DOCTYPE html>
<html lang="en"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>SIBAT {__version__} — report {record.scan_id}</title>
<style>
  :root {{ color-scheme: dark; }}
  * {{ box-sizing: border-box; }}
  body {{ margin:0; background:#060809; color:#cfd8d3;
         font:14px/1.55 ui-monospace,'JetBrains Mono','Fira Code',Menlo,monospace;
         padding:48px 24px; }}
  .wrap {{ max-width:1000px; margin:0 auto; }}
  .brand {{ letter-spacing:.35em; color:#30d158; font-weight:700; font-size:12px; }}
  .brand b {{ color:#eaeaea; }}
  h1 {{ font-size:26px; margin:10px 0 4px; color:#f2f2f2; letter-spacing:.02em; }}
  .meta {{ color:#6d7a72; font-size:12px; margin-bottom:28px; }}
  .meta span {{ margin-right:18px; }}
  .verdict {{ display:inline-block; padding:8px 14px; margin:14px 0 26px;
              border:1px solid {vcolor}66; color:{vcolor}; letter-spacing:.18em; font-size:12px;
              background:{vcolor}0d; }}
  .stats {{ display:flex; gap:14px; margin-bottom:30px; flex-wrap:wrap; }}
  .stat {{ flex:1; min-width:110px; border:1px solid #1c211e; background:#0b0f0d;
           padding:16px 18px; }}
  .stat .n {{ font-size:30px; font-weight:700; }}
  .stat .l {{ color:#6d7a72; font-size:11px; letter-spacing:.2em; margin-top:2px; }}
  table {{ width:100%; border-collapse:collapse; font-size:12.5px; }}
  th {{ text-align:left; color:#6d7a72; font-size:10.5px; letter-spacing:.22em;
       padding:10px 12px; border-bottom:1px solid #1c211e; }}
  td {{ padding:10px 12px; border-bottom:1px solid #131715; vertical-align:top; }}
  td.c {{ white-space:nowrap; color:#9aa8a0; }}
  .sub {{ color:#6d7a72; font-size:11px; margin-top:3px; word-break:break-word; }}
  .badge {{ font-size:10px; padding:2px 8px; border-radius:2px; letter-spacing:.14em; }}
  .muted {{ color:#6d7a72; }}
  footer {{ margin-top:40px; color:#4a554e; font-size:11px; line-height:1.8; }}
</style></head><body><div class="wrap">
  <div class="brand">SIBAT<b>//</b>ENGAGEMENT REPORT</div>
  <h1>{_esc(record.target)}</h1>
  <div class="meta">
    <span>SCAN #{record.scan_id}</span>
    <span>SCOPE: {_esc(record.scope_name)}</span>
    <span>START: {record.started}</span>
    <span>END: {record.finished}</span>
  </div>
  <div class="verdict">{verdict}</div>
  <div class="stats">{stat('high')}{stat('medium')}{stat('low')}{stat('info')}</div>
  {_findings_table(record.findings)}
  <footer>
    Generated by SIBAT v{__version__} — scope-locked recon framework.<br>
    All activity covered by rules of engagement: {_esc(record.scope_name)}.
    Unauthorized use against systems you do not own or are not authorized to test is illegal.
  </footer>
</div></body></html>"""


def write_report(record: ScanRecord, out_dir: str | Path = "reports") -> Path:
    out = Path(out_dir)
    out.mkdir(parents=True, exist_ok=True)
    path = out / f"report-{record.scan_id}-{record.target.replace('/', '_').replace(':', '_')}.html"
    path.write_text(render_html(record), encoding="utf-8")
    return path
